name = "cloudmail"
main = "src/index.js"
compatibility_date = "2025-06-04"
compatibility_flags = ["nodejs_compat"]
keep_vars = true

[observability]
enabled = true

[[d1_databases]]
binding = "db"
database_name = "cloudmail"
database_id = "afb36ffa-1573-48e2-81f1-6c1d32109b0e"

[[kv_namespaces]]
binding = "kv"
id = "e99362e9e63a4a289c102c800c74d6dd"

[[send_email]]
name = "SEND_EMAIL"

#[[r2_buckets]]
#binding = "r2"			#r2对象存储绑定名默认不可修改
#bucket_name = ""		#r2对象存储桶的名字

[assets]
binding = "assets"		#静态资源绑定名默认不可修改
directory = "./dist"	#前端vue项目打包的静态资源存放位置,默认dist
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 16 * * *"]	#定时任务每天晚上12点执行


[vars]
#orm_log = false
domain = ["rttx.net","08386.com","djshipregistry.com","hornmaritime.org","marinemozambique.com","marinesamoa.com"]				#邮件域名可可配置多个 示例: ["example1.com","example2.com"]
admin = "admin@rttx.net"				#管理员的邮箱	示例: admin@example.com
jwt_secret = "lkflsjlfjsg"		#jwt令牌的密钥,随便填一串字符串

[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"
